[lldb] Fix that C++ base name is only calculated when Swift plugin is…
swiftlang/llvm-project pull request #1932
Opened 2020-10-09 12:03 UTC by Teemperor

… enabled

In 41c6ab25afbb6dda179c8d995f1935aa60b9b64b I put the C++ GetBasename() call
in Module::LookupInfo behind the LLDB_ENABLE_SWIFT as it appeard to be
introduced by a downstream Swift change. However our downstream change
actually changed
```
  basename = cpp_method.GetBasename();
```
into
```
  if (swift)
    /*swift stuff*/
  else if (c++)
    basename = cpp_method.GetBasename();
```

By putting both if and the else behind LLDB_ENABLE_SWIFT this actually broke
LLDB's ability to set C++ breakpoints by function name when LLDB_ENABLE_SWIFT
wasn't set (which in turn broke the TestCPPBreakpointLocations test).

This patch moves `#ifdef LLDB_ENABLE_SWIFT` only around the Swift-specific
part and leaves the basename calculation enabled independently of Swift.

I also removed the unnecessary `else` as we can't have a method that has
both a language value of Swift and C++, so those branches are anyway mutually
exlusive and comparing the `language` enum value is cheap.

2020-10-09 12:03 UTC, Teemperor commented
@swift-ci test

2020-10-12 12:35 UTC, medismailben requested changes

2020-10-12 12:35 UTC, medismailben commented on lldb/source/Core/Module.cpp
> +              language == eLanguageTypeObjC_plus_plus) &&
May be you could use this ?

```suggestion
              Language::LanguageIsCFamily(language) &&
```

2020-10-12 12:37 UTC, medismailben approved these changes
A little nit-pick but LGTM

2020-10-12 12:45 UTC, Teemperor commented
@swift-ci test

2020-10-12 14:14 UTC, kastiglione approved these changes

2020-10-12 16:34 UTC, merged