[lldb] Remove is_variadic_ptr from TypeSystemSwift and SwiftASTContext
swiftlang/llvm-project pull request #2214
Opened 2020-12-09 21:30 UTC by lanza

This was removed from upstream and needs to be removed from `swift/next`
    usages as well.

2020-12-09 21:43 UTC, kastiglione commented
I forgot that `swift/next` would need to be updated right away. Thanks.

2020-12-09 21:43 UTC, kastiglione approved these changes

2020-12-09 21:45 UTC, kastiglione requested changes
I think there are more changes that will be required.

2020-12-09 21:45 UTC, kastiglione commented on lldb/source/Plugins/TypeSystem/Swift/TypeSystemSwiftTypeRef.h
> +  bool IsFunctionType(lldb::opaque_compiler_type_t type) override;
you'll need to update `TypeSystemSwiftTypeRef.cpp` too.

2020-12-09 21:47 UTC, kastiglione commented
`TypeSystemSwiftTypeRef.cpp` and `SwiftASTContext.cpp` each have some calls to `IsFunctionType` that will need their `nullptr` argument removed.

2020-12-10 01:17 UTC, lanza commented
I added a few more. Not sure if that's all though. There are a bunch of other build errors blocking the path atm.

2020-12-10 01:39 UTC, kastiglione approved these changes
looks good to me

2020-12-10 01:43 UTC, merged