Invert the ownership between SwiftASTContext and TypeSystemSwiftTypeR…
swiftlang/llvm-project pull request #3408
Opened 2021-10-13 18:41 UTC by adrian-prantl

…ef (NFC)

This patch introduces a new subclass SwiftASTContextForModules, which
is now owned by TypeSystemSwiftTypeRef and initialized lazily. The
TypeSystemSwiftTypeRef that corresponds to the scratch context is
still owned by SwiftASTContextForExpressions.

rdar://81717792

2021-10-13 18:41 UTC, adrian-prantl commented
@swift-ci test

2021-10-13 18:43 UTC, adrian-prantl commented
@swift-ci test

2021-10-13 20:19 UTC, augusto2112 requested changes

2021-10-13 20:19 UTC, augusto2112 commented on lldb/source/Core/Module.cpp
> +  if (auto *swift_ast =
Should this be renamed to `ts` as well?

2021-10-13 20:19 UTC, augusto2112 commented on lldb/source/Plugins/TypeSystem/Swift/SwiftASTContext.h
> +class SwiftASTContextForModule : public SwiftASTContext {
Curious: why is this new subclass necessary? Couldn't the SwiftASTContext have a pointer to its owner?

2021-10-13 20:19 UTC, augusto2112 commented on lldb/source/Plugins/TypeSystem/Swift/TypeSystemSwiftTypeRef.cpp
> +  TargetSP target_sp = target_holder->GetTarget().lock();
Can't this be null? If that's not possible maybe pass by reference?

2021-10-13 20:19 UTC, augusto2112 commented on lldb/source/Plugins/TypeSystem/Swift/TypeSystemSwiftTypeRef.cpp
> +    llvm::raw_string_ostream ss(m_description);
`ss` seems to be unused

2021-10-13 20:19 UTC, augusto2112 commented on lldb/source/Plugins/TypeSystem/Swift/TypeSystemSwiftTypeRef.cpp
> +SwiftASTContext *TypeSystemSwiftTypeRef::GetSwiftASTContext() const {
Function `TypeSystemSwiftTypeRef::IsCompatible` is still using `m_swift_ast_context` directly.

2021-10-13 20:19 UTC, augusto2112 commented on lldb/source/Plugins/TypeSystem/Swift/TypeSystemSwiftTypeRef.cpp
> +      assert(m_swift_ast_context);
Nit: this seems to just always `assert(false)` but not as clear.

2021-10-13 20:19 UTC, augusto2112 commented on lldb/source/Plugins/TypeSystem/Swift/TypeSystemSwiftTypeRef.cpp
> +SwiftASTContext *TypeSystemSwiftTypeRef::GetSwiftASTContext() const {
It might be worth logging if for whatever reason we fail to get a context.

2021-10-13 20:19 UTC, augusto2112 commented on lldb/source/Plugins/TypeSystem/Swift/TypeSystemSwiftTypeRef.cpp
> +  return GetSwiftASTContext()->ReconstructType(GetMangledTypeName(type), error);
Null pointer check?

2021-10-13 20:19 UTC, augusto2112 commented on lldb/source/Plugins/TypeSystem/Swift/TypeSystemSwiftTypeRef.cpp
> +      if (llvm::isa<SwiftASTContextForExpressions>(GetSwiftASTContext()))
I think `isa` crashes with null pointers. There's `isa_and_nonnull`

2021-10-13 20:19 UTC, augusto2112 commented on lldb/source/Plugins/TypeSystem/Swift/TypeSystemSwiftTypeRef.cpp
> +    if (llvm::dyn_cast_or_null<SwiftASTContextForExpressions>(
Nit: `isa_and_nonnull` is probably a bit clearer.

2021-10-13 20:47 UTC, adrian-prantl commented on lldb/source/Plugins/TypeSystem/Swift/SwiftASTContext.h
> +class SwiftASTContextForModule : public SwiftASTContext {
SwiftASTContextForModule has an owner, but SwiftASTContextForExpression doesn't, so I thought it would be cleaner to completely separate the two, so there's never any confusion as to what we're dealing with.

2021-10-13 20:51 UTC, adrian-prantl commented on lldb/source/Plugins/TypeSystem/Swift/TypeSystemSwiftTypeRef.cpp
> +  TargetSP target_sp = target_holder->GetTarget().lock();
!

2021-10-13 20:53 UTC, adrian-prantl commented on lldb/source/Plugins/TypeSystem/Swift/TypeSystemSwiftTypeRef.cpp
> +    llvm::raw_string_ostream ss(m_description);
ss is used to append to m_description.

2021-10-13 20:54 UTC, adrian-prantl commented on lldb/source/Plugins/TypeSystem/Swift/TypeSystemSwiftTypeRef.cpp
> +SwiftASTContext *TypeSystemSwiftTypeRef::GetSwiftASTContext() const {
We should be logging that already in CreateInstance.

2021-10-13 20:55 UTC, adrian-prantl commented on lldb/source/Plugins/TypeSystem/Swift/TypeSystemSwiftTypeRef.cpp
> +      assert(m_swift_ast_context);
Yeah, this is pointless.

2021-10-13 21:15 UTC, adrian-prantl commented
@swift-ci test

2021-10-14 01:00 UTC, adrian-prantl commented
@swift-ci test

2021-10-14 01:11 UTC, kastiglione commented on lldb/source/Plugins/LanguageRuntime/Swift/SwiftLanguageRuntimeDynamicTypeResolution.cpp
> +          dem, mangled_name.GetStringRef());
I remember these ternaries, I wanted to get back to them to remove them. There are two callers of `SwiftLanguageRuntimeImpl::GetTypeRef()`, and in both cases, they pass in a `type`, and a `TypeSystemSwiftTypeRef` derived from that type. Then here, it's derived again.

In other words, the both caller and callee are doing `type.GetTypeSystem()->GetTypeSystemSwiftTypeRef()` (ignoring the cast for simplicity). I think these ternaries can be removed.

2021-10-14 15:57 UTC, augusto2112 approved these changes
LGTM

2021-10-14 16:38 UTC, adrian-prantl commented on lldb/source/Plugins/LanguageRuntime/Swift/SwiftLanguageRuntimeDynamicTypeResolution.cpp
> +          dem, mangled_name.GetStringRef());
I will do this in a follow-up commit.

2021-10-14 16:38 UTC, merged