[lldb] Bump macOS versions to 11 on the TestPlaygrounds test
swiftlang/llvm-project pull request #3675
Opened 2021-12-13 18:36 UTC by augusto2112

This is necessary to sidestep a bug in the compiler which bumps up
triples specified as 10.x to 11

2021-12-13 18:36 UTC, augusto2112 commented
@swift-ci test

2021-12-13 18:45 UTC, augusto2112 commented
@swift-ci test

2021-12-13 19:11 UTC, adrian-prantl requested changes
That

2021-12-13 19:11 UTC, adrian-prantl commented on lldb/test/API/lang/swift/playgrounds/Contents.swift
> +@available(macOS 11.11, iOS 8.0, tvOS 8.0, watchOS 6.0, *) func newAPI() -> Int {
`11.0` there has not (yet?) been an 11.11 :-)

2021-12-13 19:11 UTC, adrian-prantl commented on lldb/test/API/lang/swift/playgrounds/TestPlaygrounds.py
> +            triple = '{}-apple-macosx11.10'.format(platform.machine())
same here

2021-12-14 12:29 UTC, augusto2112 commented
@swift-ci test

2021-12-14 17:16 UTC, adrian-prantl approved these changes
Looks good!

2021-12-14 17:21 UTC, JDevlieghere commented
Thanks Augusto!

2021-12-15 16:01 UTC, merged