[debug-info] Add support for llvm.dbg.addr in DIBuilder.
swiftlang/llvm-project pull request #3817
Opened 2022-01-19 20:39 UTC by gottesmm

I based this off of the API already create for llvm.dbg.value since both
intrinsics have the same arguments at the API level.

I added some tests exercising the API a little as well as an additional small
test that shows how one can use llvm.dbg.addr to limit the PC range where an
address value is available in the debugger. This is done by calling
llvm.dbg.value with undef and the same metadata info as one used to create the
llvm.dbg.addr.

rdar://83957028

Reviewed By: @adrian-prantl 

Differential Revision: https://reviews.llvm.org/D117442

(cherry picked from commit 7ed95d1577558f95db6b03968b561b17bbb0fec3)

2022-01-19 20:39 UTC, gottesmm commented
@swift-ci test

2022-01-20 22:17 UTC, gottesmm commented
@adrian-prantl I cherry-picked your commit.

2022-01-20 22:17 UTC, gottesmm commented
@swift-ci test

2022-01-20 22:22 UTC, adrian-prantl approved these changes

2022-01-20 22:22 UTC, adrian-prantl requested changes
I think you may have cherry-picked the wrong workaround.

2022-01-20 22:23 UTC, adrian-prantl commented
You want

2022-01-20 22:23 UTC, adrian-prantl commented
commit 24bc072edb5b157dd3ee3a7f17214ff831ea2b5c
Author: Adrian Prantl <aprantl@apple.com>
Date:   Wed Jan 19 15:33:59 2022 -0800

    Fix modules build by moving implementation into .cpp file

2022-01-20 22:26 UTC, gottesmm commented
@swift-ci test

2022-01-20 23:21 UTC, adrian-prantl approved these changes

2022-01-21 04:29 UTC, gottesmm commented
TSAN race test failed...

2022-01-21 04:29 UTC, gottesmm commented
@swift-ci test macOS platform

2022-01-21 05:34 UTC, gottesmm commented
@swift-ci test macOS platform

2022-01-21 13:42 UTC, merged