[lldb] Fix invalid use of mutating keyword in generated expressions
swiftlang/llvm-project pull request #4225
Opened 2022-04-14 21:33 UTC by augusto2112

Prevent conditional logic from falling through to adding the mutating
keyword when evaluating Swift expressions inside of a a function whose
self type is a dynamic Self.

After determining the type of self, resolve instances of DynamicSelfType
to their self type. This allows consumers to properly determine when a
type is a class, for example, which is not possible when using the
dynamic self directly.

2022-04-14 21:33 UTC, augusto2112 commented
@swift-ci test

2022-04-14 21:33 UTC, augusto2112 commented
This picks up where https://github.com/apple/llvm-project/pull/2940 left and adds the test

2022-04-14 22:11 UTC, kastiglione approved these changes

2022-04-14 22:12 UTC, kastiglione commented on lldb/test/API/lang/swift/designated_initializer_self/TestDesignatedInitializerSelf.py
> +lldbinline.MakeInlineTest(__file__, globals(), decorators=[swiftTest, skipUnlessFoundation])
is `skipUnlessFoundation` required?

2022-04-14 22:30 UTC, augusto2112 commented on lldb/test/API/lang/swift/designated_initializer_self/TestDesignatedInitializerSelf.py
> +lldbinline.MakeInlineTest(__file__, globals(), decorators=[swiftTest, skipUnlessFoundation])
Nope, will remove it.

2022-04-14 22:36 UTC, augusto2112 commented
@swift-ci test

2022-04-15 20:21 UTC, adrian-prantl requested changes
Can you make this PR against the `release/5.7` branch instead?

2022-04-18 13:27 UTC, augusto2112 commented
@swift-ci test

2022-04-18 17:05 UTC, augusto2112 commented
@swift-ci test macOS

2022-04-19 12:55 UTC, merged