[lldb] Fix swift-healtcheck channel definition
swiftlang/llvm-project pull request #4241
Opened 2022-04-19 23:36 UTC by kastiglione

In 41098357c8deb995a06deeb302ef3061e079b733, there ended up being two definitions of `g_channel`, the `Log::Channel` instance backing the `swift-healthcheck` command. This removes the duplicate.

rdar://91652023

2022-04-19 23:36 UTC, kastiglione commented
@swift-ci test

2022-04-20 15:54 UTC, medismailben approved these changes
Very minor nit: I'd prefer to have everything in the `LogChannelSwift` struct to be self-contained, including the static `Log::Channel g_channel`, but other than that LGTM

2022-04-20 19:45 UTC, adrian-prantl requested changes
Please make sure to rebase this on the swift/release/5.7 branch.

2022-04-20 19:46 UTC, adrian-prantl commented
Is there a reason why this wasn't caught by the test suite? Is is only an issue in lldb-rpc-server?

2022-04-20 21:18 UTC, kastiglione commented
@swift-ci test

2022-04-20 21:19 UTC, kastiglione commented
> Is there a reason why this wasn't caught by the test suite?

I will add a test that calls the command, scrapes the output for the path, and checks its contents.

2022-04-20 21:41 UTC, kastiglione commented
> have everything in the `LogChannelSwift` struct to be self-contained, including the static `Log::Channel g_channel`

@medismailben if it's a minor nit, I will keep it as is. All things being equal, I value keeping it out of the header (and scoped to the source file) instead of scoped into the struct (and somewhat exposing it).

2022-04-21 16:06 UTC, medismailben commented
> > have everything in the `LogChannelSwift` struct to be self-contained, including the static `Log::Channel g_channel`
> 
> @medismailben if it's a minor nit, I will keep it as is. All things being equal, I value keeping it out of the header (and scoped to the source file) instead of scoped into the struct (and somewhat exposing it).

Sounds good

2022-04-21 17:17 UTC, merged