[lldb] Look through existential types when handling typealiases in SwiftASTContext to correctly handle `AnyObject` existentials.
swiftlang/llvm-project pull request #4852
Opened 2022-06-18 01:27 UTC by hborla

https://github.com/apple/swift/pull/41909 updates the representation of `Any` and `AnyObject` in the Swift frontend to use `ExistentialType`. Typealiases like `AnyObject` can be used as existential types, which are represented as `ExistentialType(TypeAliasType)`, so LLDB should look through to an existential type's constraint when checking whether it has a typealias.

2022-06-18 01:30 UTC, hborla commented
https://github.com/apple/swift/pull/41909

@swift-ci please test

2022-06-18 17:13 UTC, adrian-prantl approved these changes
Thanks!

2022-06-18 17:16 UTC, adrian-prantl requested changes
Sorry — just realized that this PR is on the wrong branch.
The Swift `release/5.7` branch goes with llvm-project `swift/release/5.7`. Any commit there also needs to be (manually) cherrypicked to `stable/20220421` and to `next`. You can push these cherry-picks without testing.

2022-06-23 00:03 UTC, hborla commented
@adrian-prantl whoops, I'll get that fixed now, thank you!!

2022-06-23 00:03 UTC, closed without merging