[clang][cas] ScanAndUpdateArgs: Keep the preprocessor option macros for the include-tree
swiftlang/llvm-project pull request #5205
Opened 2022-08-26 14:40 UTC by akyrtzi

Even though the macros are written in the predefines buffer which is saved in the include-tree root,
we still need to keep them as preprocessor options so that they are preserved in a PCH file and
compared with the preprocessor options of another invocation that uses the PCH.

2022-08-26 14:40 UTC, akyrtzi commented
@swift-ci Please test

2022-08-26 14:55 UTC, akyrtzi commented
@swift-ci Please test

2022-08-26 16:26 UTC, akyrtzi commented
@swift-ci test linux platform

2022-08-26 20:15 UTC, akyrtzi commented
I had missed including the test case.

2022-08-26 20:15 UTC, akyrtzi commented
@swift-ci Please test

2022-08-26 21:25 UTC, akyrtzi commented on clang/test/CAS/cmd-macro-and-pch.c
> +// RUN: %clang @%t/tu.rsp -fsyntax-only
This would emit a warning "'SOME_MACRO' redefined" before the change.

2022-08-26 23:25 UTC, benlangmuir commented
> so that they are preserved in a PCH file and compared with the preprocessor options of another invocation that uses the PCH

I don't understand what this means - is this about loading the PCH in the scanner, or in the compiler?  By the time we get to the compiler, shouldn't we have already validated everything?

2022-08-26 23:30 UTC, akyrtzi commented
> is this about loading the PCH in the scanner, or in the compiler?

It's about loading the PCH in the scanner. There's code in the ASTReader that checks whether there are differences in options between the PCH and the invocation and updates the `Predefines` buffer accordingly.

The change is primarily about preserving the options so they are recorded when writing out the PCH file and read when the scanner loads it.

2022-08-26 23:33 UTC, benlangmuir commented
Can we drop the options when we create the final compiler invocation?

2022-08-26 23:41 UTC, akyrtzi commented
You mean only preserve them when the output is a PCH file, otherwise remove them? Note that removing them doesn't actually offer canonicalization benefits because they affect the `Predefines` buffer, which is an input for the compilation key, so it wasn't clear to me there's an advantage to diverging based on output.

2022-08-26 23:45 UTC, benlangmuir approved these changes
> You mean only preserve them when the output is a PCH file, otherwise remove them?

Yeah, that's what I had in mind.

> Note that removing them doesn't actually offer canonicalization benefits because they affect the Predefines buffer, which is an input for the compilation key, so it wasn't clear to me there's an advantage to diverging based on output.

Just seems nice to drop redundant information. Not worth blocking your change over, so approved the PR.

2022-08-27 00:15 UTC, akyrtzi commented
@swift-ci Please test

2022-08-27 00:16 UTC, akyrtzi commented
> Just seems nice to drop redundant information.

I made such a change, please take another look 🙏

2022-08-27 00:49 UTC, benlangmuir requested changes
Nice, thanks!

2022-08-27 00:49 UTC, benlangmuir approved these changes

2022-08-27 03:00 UTC, merged