LanguageRuntime: ensure that we have a scratch context
swiftlang/llvm-project pull request #6641
Opened 2023-04-13 17:29 UTC by compnerd

We would previously not ensure that we had an initialised scratch context before we would check if we encountered any fatal errors. Protect against this case, while the experience may be degraded, this prevents the debugger from terminating abnormally.

2023-04-13 17:29 UTC, compnerd commented
CC: @adrian-prantl @JDevlieghere @bulbazord @kastiglione

2023-04-13 17:29 UTC, compnerd commented
@swift-ci please test

2023-04-13 17:45 UTC, adrian-prantl requested changes
This is great, but the right branches for this are swift/release/5.9 (which merges into stable/20221013) and next.

2023-04-13 17:47 UTC, compnerd commented
@swift-ci please test

2023-04-13 17:51 UTC, adrian-prantl approved these changes

2023-04-13 19:23 UTC, compnerd commented
@swift-ci please test

2023-04-13 20:28 UTC, compnerd commented
@swift-ci please test Windows platform

2023-04-14 01:25 UTC, compnerd commented
@swift-ci please test macOS platform

2023-04-14 14:52 UTC, merged