[lldb] Iterate over a snapshot of the modules to be added in SetupRef…
swiftlang/llvm-project pull request #7091
Opened 2023-07-19 22:28 UTC by augusto2112

…lection

SwiftLanguageRuntimeImpl::SetupReflection is potentially recursive. To guard against any potential problems of iterating over the modules to be added list and mutating it at the same time, create a snapshot of said list and iterate over that instead.

rdar://108767207

2023-07-19 22:29 UTC, augusto2112 commented
@swift-ci test

2023-07-19 23:54 UTC, adrian-prantl approved these changes

2023-07-20 00:00 UTC, adrian-prantl requested changes

2023-07-20 00:00 UTC, adrian-prantl commented on lldb/source/Plugins/LanguageRuntime/Swift/SwiftLanguageRuntime.cpp
m_modules_to_add has been cleared when you reach the Progress initializer. I think you want the snapshot here?

2023-07-21 17:00 UTC, augusto2112 commented
@swift-ci test

2023-07-21 19:13 UTC, augusto2112 commented
@swift-ci test windows

2023-07-21 19:34 UTC, adrian-prantl approved these changes

2023-07-21 21:00 UTC, merged