Add new OutputKind 'CASIDFile' for MCCAS replay.
swiftlang/llvm-project pull request #8077
Opened 2024-01-30 01:48 UTC by rastogishubham

When using MCCAS replay with the option -fcas-emit-casid-file, we would see the error:

fatal error: caching backend error: cached output file has unknown path <path-to-file>/file.casid

To fix this we need to add the casid file to the KindMap and add a new OutputKind for it as well. This patch adds that functionality.

2024-01-30 19:32 UTC, rastogishubham commented
@swift-ci please test

2024-01-30 19:32 UTC, rastogishubham commented
@swift-ci please test llvm

2024-01-30 19:39 UTC, cachemeifyoucan requested changes
That is not the correct approach. CASID file should not go into the CAS, and writing a CASID into the CAS should generally be avoided. CASID file content is just the CASID of the main output, so clang should be able to render that directly. I will make that a special case, rather than an official output from clang.

2024-01-30 19:49 UTC, benlangmuir commented
To make sure I understand, @cachemeifyoucan are you suggesting not writing the casid file through the output backend at all, or is the special case inside the cas backend to avoid ingesting this output?

2024-01-30 19:51 UTC, cachemeifyoucan commented
> To make sure I understand, @cachemeifyoucan are you suggesting not writing the casid file through the output backend at all, or is the special case inside the cas backend to avoid ingesting this output?

I prefer not to write it out through CAS output backend (you can still go thorough the backend with a filtered backend at the first place).

2024-01-31 18:33 UTC, adrian-prantl commented on clang/include/clang/Frontend/CompileJobCacheResult.h
> +    CASIDFile, ///< A CASID file emitted next to the object file when the
Total nit: When it doesn't fit on a single line the ///< comments are better replaced with a /// comment on the line above.

2024-01-31 18:34 UTC, adrian-prantl approved these changes

2024-01-31 18:36 UTC, adrian-prantl commented
Nevermind, please follow @cachemeifyoucan 's suggestions.

2024-03-02 01:06 UTC, rastogishubham commented
@cachemeifyoucan @benlangmuir how does this look?

2024-03-02 01:35 UTC, cachemeifyoucan reviewed
Please always write a test case when you fix a bug.

2024-03-04 23:29 UTC, cachemeifyoucan approved these changes
LGTM

2024-03-04 23:30 UTC, cachemeifyoucan commented
@swift-ci please test llvm

2024-03-05 19:23 UTC, merged