Patch -[no-]gtest-sharding flags into lit
swiftlang/llvm-project pull request #9066
Opened 2024-08-07 22:21 UTC by kendalharland

This branch uses a version of LLVM's `lit` testing tool that contains two bugs that prevent marking tests as XFAIL using either the `--xfail` flag or the `LIT_XFAIL` environment variable. These issues are outlined in https://github.com/llvm/llvm-project/issues/102264 and https://github.com/llvm/llvm-project/issues/102265. This PR cherry-picks support for the `--gtest-sharding` and `--no-gtest-sharding` flags into the `stable/20230725` branch so that gtest sharding can be disabled by the user, allowing the use of xfail inputs. The motivation for this change is that I'm working on running LLDB tests as part of the Windows x64 Swift toolchain release builds, and a few hundred of the tests are currently failing. I need to mark them as XFAIL with issue links and fix each test over time.  Marking them as XFAIL using these inputs is preferred over marking them as XFAIL in the test source code using decorators, as the upstream versions of these tests are passing in `llvm/llvm-project` and this is less invasive.

2024-08-08 16:37 UTC, compnerd requested changes
Please re-cherry-pick with `-x` to track the original commit upstream.

2024-08-08 17:30 UTC, compnerd approved these changes

2024-08-08 17:31 UTC, compnerd commented
@swift-ci please test

2024-08-09 00:10 UTC, kendalharland commented
I'll need help merging since I don't have write access

2024-08-09 13:17 UTC, merged