Swift MCCAS object files are 0 bytes on cache miss
swiftlang/llvm-project pull request #9164
Opened 2024-08-21 18:06 UTC by rastogishubham

When clang caching and MCCAS are enabled, on a cache miss, the object file is not written to in MachOCASWriter, instead the replay code is rerun and the object file is serialized and written out. However, in swift, the replay code isn't run on a cache miss at all, and it expects the object writer to write to the object file.

This patch makes it so that on a cache miss, the MachOCASWriter always writes to the raw_ostream buffer for the object file and doesn't serialize the object file in the replay code.

rdar://134425492 ([MCCAS] Fix bug with swift caching where object files are 0 bytes in size)

2024-08-21 18:07 UTC, rastogishubham commented
@swift-ci please test

2024-08-21 18:07 UTC, rastogishubham commented
@swift-ci please test llvm

2024-08-21 18:14 UTC, adrian-prantl commented on llvm/lib/MC/MachOCASWriter.cpp
>      cantFail((*ResultCallBack)(CASObj.getID()));
Why did you remove the verification code?

2024-08-21 18:15 UTC, rastogishubham commented on llvm/lib/MC/MachOCASWriter.cpp
>      cantFail((*ResultCallBack)(CASObj.getID()));
It's not removed, it is a fallthrough to the verification code below

2024-08-21 19:38 UTC, adrian-prantl approved these changes

2024-08-21 19:46 UTC, cachemeifyoucan requested changes

2024-08-21 19:46 UTC, cachemeifyoucan commented on clang/lib/Frontend/CompileJobCache.cpp
> +  if (JustComputedResult)
I doubt this works. This will probably cause the output being written twice when CASBackend or CASID output is used.

2024-08-23 18:10 UTC, rastogishubham commented
@cachemeifyoucan I added a test for the `-fcasid-output` option, when the `-fcasid-output` option is used, the OnDiskOutput is filtered out:

```
IntrusiveRefCntPtr<llvm::vfs::OutputBackend> OnDiskOutputs =
      llvm::makeIntrusiveRefCnt<llvm::vfs::OnDiskOutputBackend>();
  if (WriteOutputAsCASID) {
    OnDiskOutputs = llvm::vfs::makeFilteringOutputBackend(
        OnDiskOutputs,
        [this](StringRef ResolvedPath, std::optional<llvm::vfs::OutputConfig>) {
          return ResolvedPath != this->OutputFile;
        });
  }
  ```
Therefore, even on a cache miss, we do need to go into the replay code, and that will be the case for both MCCAS and file based caching, but as long as `-fcasid-output` is not used, MCCAS should serialize the object file in the `MachOCASWriter` which will make it so that it works correctly with swift MCCAS as well.

2024-08-23 18:10 UTC, rastogishubham commented
@swift-ci please test

2024-08-23 18:11 UTC, rastogishubham commented
@swift-ci please test

2024-08-27 17:44 UTC, rastogishubham commented
@swift-ci please test macOS

2024-08-27 17:44 UTC, cachemeifyoucan approved these changes

2024-08-28 01:45 UTC, merged