Workaround invalid reloc 315 on aarch64 Linux
swiftlang/llvm-project pull request #9339
Opened 2024-09-25 20:30 UTC by bnbarham

`gold` fails to link `libswiftDispatch.so` on aarch64 Linux due to:
```
/usr/bin/ld.gold: error: Invalid/unrecognized reloc reloc 315.
/usr/bin/ld.gold: internal error in global, at ../../gold/aarch64.cc:6398
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

Attempt to workaround this via disabling
`SupportIndirectSymViaGOTPCRel`.

rdar://135050296

2024-09-25 21:08 UTC, compnerd requested changes
Can we expose this as a flag instead? I don't think that we should be making this change. We are also hitting this on Android and are "working around" it by using the just built lld.

2024-09-26 03:25 UTC, bnbarham commented
> Can we expose this as a flag instead? I don't think that we should be making this change. We are also hitting this on Android and are "working around" it by using the just built lld.

I'd prefer to get this change in to unblock rebranch, then see what the outcome of https://github.com/llvm/llvm-project/pull/78003#issuecomment-2375465788 ends up being (and either cherry-picking that, or using the flag if it's added). Is that reasonable to you?

2024-09-26 03:26 UTC, bnbarham commented
@swift-ci please test llvm

2024-10-08 21:54 UTC, bnbarham commented
@swift-ci please test

2024-10-08 21:56 UTC, bnbarham commented
> Can we expose this as a flag instead? I don't think that we should be making this change. We are also hitting this on Android and are "working around" it by using the just built lld.

I'd like to get this in ASAP as we have no idea if there's downstream aarch64 failures - I should have merged this last week really 😅. I agree passing a flag through probably makes more sense, so we can look at that separately.

2024-10-09 02:15 UTC, bnbarham commented
Failure is unrelated - it just started failing on tip.

2024-10-09 02:16 UTC, bnbarham commented
@swift-ci please llvm test

2024-10-09 02:16 UTC, bnbarham commented
@swift-ci please test llvm

2024-10-09 03:47 UTC, merged