[lldb] Fix thread plan to step through swift_task_switch
swiftlang/llvm-project pull request #9452
Opened 2024-10-21 15:00 UTC by felipepiovezan

This PR removes ThreadPlanStepInAsync and replaces it with a simpler plan that _only_ handles swift_task_switch.
Please review each commit individually.

2024-10-21 15:02 UTC, felipepiovezan commented
@jimingham I am particularly interested in your thoughts about the second commit message / implementation.

2024-10-21 15:48 UTC, felipepiovezan commented
Ah, I forgot to include the test for the second commit. Will update the PR momentarily.

2024-10-21 17:22 UTC, jimingham commented on lldb/source/Plugins/LanguageRuntime/Swift/SwiftLanguageRuntimeNames.cpp
> +  uint64_t resume_fn_ptr = reg_ctx->ReadRegisterAsUnsigned(resume_fn_reg, 0);
ConvertRegisterKindToRegisterNumber could fail (on an architecture that passes ALL arguments on the stack, so not likely, but formally it could.)

2024-10-21 17:23 UTC, jimingham commented
The previous plan handled the case where the task switch ended up with the resume code called on another thread.  I didn't see how your patch handled that?

2024-10-21 17:36 UTC, felipepiovezan commented
> The previous plan handled the case where the task switch ended up with the resume code called on another thread. I didn't see how your patch handled that?

Mmmm I see. I need to fix that. Let me put this PR in draft mode for now

2024-10-21 17:46 UTC, kastiglione requested changes
Apologies if I've overlooked the details, but can you provide explanation of how this handles multiple tasks going through the same codepath? One of the responsibilities of `ThreadPlanStepInAsync` is to capture the async context before the step, and when its internal breakpoint hits, it checks that the async context is the same. When the async context is different, execution continues. In other words, stepping from one task shouldn't stop at the same resume function for a different task.

2024-10-21 17:46 UTC, kastiglione commented
ah, Jim has said the same…

2024-11-07 21:43 UTC, felipepiovezan commented
Replaced by https://github.com/swiftlang/llvm-project/pull/9546

2024-11-07 21:43 UTC, closed without merging