[DNM] [lldb] Update for removal of `ModuleDecl::addFile`
swiftlang/llvm-project pull request #9618
Opened 2024-11-16 23:04 UTC by hamishknight

2024-11-16 23:05 UTC, hamishknight commented
https://github.com/swiftlang/swift/pull/77666

@swift-ci please test

2024-11-16 23:16 UTC, hamishknight commented on lldb/source/Plugins/TypeSystem/Swift/SwiftASTContext.h
> +  /// imported by each file of the module.
Need to remove this

2024-11-17 14:21 UTC, hamishknight commented
https://github.com/swiftlang/swift/pull/77666

@swift-ci please test

2024-11-21 12:41 UTC, hamishknight commented
https://github.com/swiftlang/swift/pull/77666

@swift-ci please test

2024-11-21 17:00 UTC, adrian-prantl requested changes
Can you rebase this PR on swift/release/6.1?

2024-11-21 17:07 UTC, hamishknight commented
@adrian-prantl This is targeting `main`, it doesn't need to be in 6.1

2024-11-21 18:56 UTC, adrian-prantl approved these changes
In that case LGTM — please don't forget to also create a matching PR that cherry-picks this to `next`!

2024-11-21 18:56 UTC, adrian-prantl commented
You can/should merge the next cherry-pick immediately without review or testing.

2024-11-21 20:16 UTC, merged