Only no-op ld64.lld on Apple hosts
swiftlang/llvm-project pull request #9698
Opened 2024-12-06 01:02 UTC by kabiroberai

Following #8119, invoking `ld64.lld` results in the error `This version of lld does not support linking for platform [macOS/iOS/...]`.

The rationale behind the original change was to make sure people don't accidentally use lld instead of dyld's ld64 on macOS, given that new macOS toolchains ship with lld for linking ELF binaries. However, this had the unintended effect of also making it impossible to cross-compile MachO binaries on _Linux_ hosts with the Swift toolchain — a use case that is otherwise fully possible with Swift SDKs.

This PR updates the patch such that we only abort when linking Darwin binaries on Apple host platforms.

2024-12-06 10:15 UTC, MaxDesiatov commented
@swift-ci test

2024-12-11 20:15 UTC, kabiroberai commented
heya @kubamracek, would be awesome if you could take a look at this! really hope we can land this in time to be cherry-picked into 6.1

2024-12-12 18:12 UTC, rauhul requested changes

2024-12-12 18:12 UTC, rauhul commented on lld/MachO/InputFiles.cpp
>    error("This version of lld does not support linking for platform " + getPlatformName(platformInfos.front().target.Platform));
Can we add a warning to say linking macho on via ld64.lld is unsupported and use at your own risk? (for non-apple)

2026-09-21 02:56 UTC, closed without merging