[lldb] Merge SwiftLanguageRuntimeImpl back into SwiftLanguageRuntime (NFC)
swiftlang/llvm-project pull request #9775
Opened 2024-12-19 21:50 UTC by adrian-prantl

The lazy initialization of the Runtime used to be necessary before the
ReflectionContext was able to initialized lazily. Since we can just
defer initializing ReflectionContext, we can get rid of the extra
indirection.

rdar://139995777

2024-12-19 21:50 UTC, adrian-prantl commented
@swift-ci test

2024-12-19 21:51 UTC, JDevlieghere approved these changes

2024-12-19 21:53 UTC, JDevlieghere requested changes

2024-12-19 21:53 UTC, JDevlieghere commented on lldb/source/Plugins/LanguageRuntime/Swift/SwiftLanguageRuntimeImpl.h
> +#error cxxcxxx
???

2024-12-19 21:58 UTC, adrian-prantl commented on lldb/source/Plugins/LanguageRuntime/Swift/SwiftLanguageRuntimeImpl.h
> +#error cxxcxxx
I meant to `git rm` this. Done!

2024-12-19 21:58 UTC, JDevlieghere approved these changes

2024-12-19 23:39 UTC, adrian-prantl commented
@swift-ci test

2024-12-20 01:00 UTC, adrian-prantl commented
@swift-ci test

2024-12-20 04:57 UTC, merged